input_data_path: "data/raw/heart.csv"
output_model_path: "models/model.pkl"
metric_path: "models/metrics.json"
splitting_params:
  val_size: 0.25
  random_state: 42
train_params:
  model_type: "LogisticRegression"
  max_iter: 20
feature_params:
  categorical_features:
    - "sex"
    - "cp"
    - "fbs"
    - "restecg"
    - "exang"
    - "slope"
    - "thal"
    - "ca"
  numerical_features:
    - "age"
    - "trestbps"
    - "thalach"
    - "oldpeak"
  numerical_grouped_features:
    - "chol"
  target_col: "target"

